{"name": "Проверка создания пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x561cfffdf67a <unknown>\n#1 0x561cffa5e566 <unknown>\n#2 0x561cffa55470 <unknown>\n#3 0x561cffa46926 <unknown>\n#4 0x561cffa4872b <unknown>\n#5 0x561cffa46eb1 <unknown>\n#6 0x561cffa46650 <unknown>\n#7 0x561cffa46302 <unknown>\n#8 0x561cffa44142 <unknown>\n#9 0x561cffa4492a <unknown>\n#10 0x561cffa61a99 <unknown>\n#11 0x561cffafcee5 <unknown>\n#12 0x561cffad6632 <unknown>\n#13 0x561cffafc328 <unknown>\n#14 0x561cffad6403 <unknown>\n#15 0x561cffaa2b02 <unknown>\n#16 0x561cffaa37c1 <unknown>\n#17 0x561cfffa3448 <unknown>\n#18 0x561cfffa72af <unknown>\n#19 0x561cfff8a8d9 <unknown>\n#20 0x561cfffa7e55 <unknown>\n#21 0x561cfff7013f <unknown>\n#22 0x561cfffcc4b8 <unknown>\n#23 0x561cfffcc693 <unknown>\n#24 0x561cfffde613 <unknown>\n#25 0x7f2c2a90db7b <unknown>", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"dceae66f68abe1d6c5822532ef67c79b\")>\nbase_url = 'http://31.59.174.108'\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"dceae66f68abe1d6c5822532ef67c79b\")>\nregistration_data = {'email': 'test_user123@mail.ru', 'name': 'User25', 'password': 'qwertyui'}\n\n    @allure.epic(\"Аутентификация и авторизация\")\n    @allure.feature(\"Регистрация пользователей\")\n    @allure.suite(\"Смоук тесты\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.tag(\"smoke\", \"ui\")\n    @allure.label(\"owner\", \"QA - evgeny_gord\")\n    @allure.id(\"TEST-123\")\n    @allure.title(\"Проверка создания пользователя\")\n    @allure.description(\"\"\"\n    Этот тест проверяет:\n    - Регистрацию пользователя с позитивным сценарием\n    - Проверка успеха прохождения регистрации\n    ИЛИ\n    - Проверка предупреждения, что пользователь уже создан с таким email\n    \"\"\")\n    @allure.link(\"https://jira.example.com/TEST-123\", name=\"JIRA Task\")\n    @allure.issue(\"BUG-456\", \"https://bugtracker.com/BUG-456\")\n    @allure.testcase(\"TC-789\", \"https://testcase.com/TC-789\")\n    def test_positive_registration(browser, base_url, wait, registration_data):\n        # driver = webdriver.Chrome(service=Service(executable_path='C:/chromedriver.exe'))\n        # driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n        # driver.get(url)\n        with allure.step('Переход на страницу Регистрации'):\n>           browser.get(f\"{base_url}/sign_up\")\n\ntests/test_ui/test_first.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f66f509a570>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x561cfffcc693 \\\\u003Cunknown>\\\\n#24 0x561cfffde613 \\\\u003Cunknown>\\\\n#25 0x7f2c2a90db7b \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\") if isinstance(message, dict) else None\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=141.0.7390.107)\nE       Stacktrace:\nE       #0 0x561cfffdf67a <unknown>\nE       #1 0x561cffa5e566 <unknown>\nE       #2 0x561cffa55470 <unknown>\nE       #3 0x561cffa46926 <unknown>\nE       #4 0x561cffa4872b <unknown>\nE       #5 0x561cffa46eb1 <unknown>\nE       #6 0x561cffa46650 <unknown>\nE       #7 0x561cffa46302 <unknown>\nE       #8 0x561cffa44142 <unknown>\nE       #9 0x561cffa4492a <unknown>\nE       #10 0x561cffa61a99 <unknown>\nE       #11 0x561cffafcee5 <unknown>\nE       #12 0x561cffad6632 <unknown>\nE       #13 0x561cffafc328 <unknown>\nE       #14 0x561cffad6403 <unknown>\nE       #15 0x561cffaa2b02 <unknown>\nE       #16 0x561cffaa37c1 <unknown>\nE       #17 0x561cfffa3448 <unknown>\nE       #18 0x561cfffa72af <unknown>\nE       #19 0x561cfff8a8d9 <unknown>\nE       #20 0x561cfffa7e55 <unknown>\nE       #21 0x561cfff7013f <unknown>\nE       #22 0x561cfffcc4b8 <unknown>\nE       #23 0x561cfffcc693 <unknown>\nE       #24 0x561cfffde613 <unknown>\nE       #25 0x7f2c2a90db7b <unknown>\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException"}, "description": "\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n", "steps": [{"name": "Переход на страницу Регистрации", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=141.0.7390.107)\nStacktrace:\n#0 0x561cfffdf67a <unknown>\n#1 0x561cffa5e566 <unknown>\n#2 0x561cffa55470 <unknown>\n#3 0x561cffa46926 <unknown>\n#4 0x561cffa4872b <unknown>\n#5 0x561cffa46eb1 <unknown>\n#6 0x561cffa46650 <unknown>\n#7 0x561cffa46302 <unknown>\n#8 0x561cffa44142 <unknown>\n#9 0x561cffa4492a <unknown>\n#10 0x561cffa61a99 <unknown>\n#11 0x561cffafcee5 <unknown>\n#12 0x561cffad6632 <unknown>\n#13 0x561cffafc328 <unknown>\n#14 0x561cffad6403 <unknown>\n#15 0x561cffaa2b02 <unknown>\n#16 0x561cffaa37c1 <unknown>\n#17 0x561cfffa3448 <unknown>\n#18 0x561cfffa72af <unknown>\n#19 0x561cfff8a8d9 <unknown>\n#20 0x561cfffa7e55 <unknown>\n#21 0x561cfff7013f <unknown>\n#22 0x561cfffcc4b8 <unknown>\n#23 0x561cfffcc693 <unknown>\n#24 0x561cfffde613 <unknown>\n#25 0x7f2c2a90db7b <unknown>\n\n", "trace": "  File \"/app/tests/test_ui/test_first.py\", line 41, in test_positive_registration\n    browser.get(f\"{base_url}/sign_up\")\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 483, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1760786757753, "stop": 1760786760969}], "attachments": [{"name": "stdout", "source": "fe716674-585b-4097-bdf9-c09761c6553a-attachment.txt", "type": "text/plain"}], "start": 1760786757753, "stop": 1760786760983, "uuid": "a311bccb-f402-4726-af0c-1ca01f4f2656", "historyId": "43c63fead18b01a08ec1d8de921e11ef", "testCaseId": "43c63fead18b01a08ec1d8de921e11ef", "fullName": "tests.test_ui.test_first#test_positive_registration", "labels": [{"name": "suite", "value": "Смоук тесты"}, {"name": "as_id", "value": "TEST-123"}, {"name": "epic", "value": "Аутентификация и авторизация"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "Регистрация пользователей"}, {"name": "owner", "value": "QA - evgeny_gord"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.test_ui"}, {"name": "host", "value": "1b79bd22dc0c"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui.test_first"}], "links": [{"type": "tms", "url": "TC-789", "name": "https://testcase.com/TC-789"}, {"type": "issue", "url": "BUG-456", "name": "https://bugtracker.com/BUG-456"}, {"type": "link", "url": "https://jira.example.com/TEST-123", "name": "JIRA Task"}], "titlePath": ["tests", "test_ui", "test_first.py"]}